---
- hosts: all
  sudo: true
  tasks:
    - apt: update_cache=yes
    - apt: name=nano state=absent
    - apt: name={{item}} state=present
      with_items:
        - mc
        - htop
        - vim
        - git
        - curl
    - command: bash -c 'curl -sSL https://get.docker.com/ | sh'
    - command: bash -c 'curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.deb.sh | bash'
    - apt: name=gitlab-ci-multi-runner state=present
    - command: gitlab-ci-multi-runner register --non-interactive --url {{url}} --registration-token {{token}} --name {{name}} --tag-list '' --executor docker --docker-image debian:8
      when: url is not none and token is not none and name is not none
    - fail: msg="You must provide ENV variables $url, $token, $name. Runner has not been registred yet."
      when: not (url is not none and token is not none and name is not none)

